-- Shadowing lessons remain private until an administrator reviews and publishes
-- the timestamped transcript generated by the ingest workflow.
alter table public.shadow
  add column if not exists title text not null default '',
  add column if not exists description text not null default '',
  add column if not exists thumbnail_url text,
  add column if not exists category text not null default 'general',
  add column if not exists difficulty text not null default 'intermediate'
    check (difficulty in ('novice', 'intermediate', 'advanced')),
  add column if not exists publication_status text not null default 'draft'
    check (publication_status in ('draft', 'processing', 'ready_for_review', 'published', 'failed')),
  add column if not exists processing jsonb,
  add column if not exists created_by text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists published_at timestamptz;

update public.shadow
set publication_status = 'draft', updated_at = now()
where id = 'sample' and publication_status = 'published';

create table if not exists public.shadow_processing_jobs (
  lesson_id text primary key references public.shadow(id) on delete cascade,
  youtube_video_id text not null,
  requested_caption_language text not null default 'en',
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'ready_for_review', 'needs_audio_stt', 'failed', 'published')),
  stage text not null default 'queued',
  progress integer not null default 0 check (progress between 0 and 100),
  caption_source text,
  audio_source_url text,
  error_message text,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.shadow enable row level security;
alter table public.shadow_processing_jobs enable row level security;

drop policy if exists "public read" on public.shadow;
drop policy if exists "shadow lessons public read" on public.shadow;
create policy "shadow lessons public read" on public.shadow
  for select to anon, authenticated
  using (publication_status = 'published');

drop policy if exists "shadow lessons admin read" on public.shadow;
create policy "shadow lessons admin read" on public.shadow
  for select to authenticated
  using (public.is_admin());

drop policy if exists "shadow processing jobs admin read" on public.shadow_processing_jobs;
create policy "shadow processing jobs admin read" on public.shadow_processing_jobs
  for select to authenticated
  using (public.is_admin());

grant select on public.shadow to anon, authenticated;
grant select on public.shadow_processing_jobs to authenticated;
